server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@112.221.156.34:12345:xe
    username: KH08_KTY
    password: KH1234


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.myproject.project1.member.vo
